# Generated by Django 6.0.6 on 2026-07-06 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('location', models.CharField(max_length=200, verbose_name='Расположение')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('installed_at', models.DateField(verbose_name='Дата установки')),
            ],
            options={
                'verbose_name': 'Станция',
                'verbose_name_plural': 'Станции',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(verbose_name='Дата и время наблюдения')),
                ('parameter', models.CharField(choices=[('temperature', 'Температура'), ('humidity', 'Влажность'), ('pressure', 'Давление'), ('pm25', 'PM2.5')], max_length=20, verbose_name='Параметр')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('unit', models.CharField(max_length=20, verbose_name='Единица измерения')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='monitoring.station', verbose_name='Станция')),
            ],
            options={
                'verbose_name': 'Наблюдение',
                'verbose_name_plural': 'Наблюдения',
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['station'], name='monitoring__station_cbea74_idx'), models.Index(fields=['observed_at'], name='monitoring__observe_90f262_idx')],
            },
        ),
    ]
